import AVFoundation
import BoloKit
import Observation

/// Plays Gujarati lines two ways, and lets Luke compare them:
///  - Recorded (AI): neural-TTS clips generated by the audio workflow and bundled in Audio/.
///  - iPhone voice: the best installed gu-IN system voice (premium, then enhanced, then default).
/// The audio session uses the playback category, so lines play even with the silent switch on.
@MainActor
@Observable
final class AudioService: NSObject {
    enum Source: String, CaseIterable, Identifiable {
        case recorded
        case system

        var id: String { rawValue }
        var title: String { self == .recorded ? "Recorded (AI)" : "iPhone voice" }
    }

    private(set) var manifest: AudioManifest?
    private(set) var systemVoice: AVSpeechSynthesisVoice?
    /// Key of the line playing right now, for the play buttons.
    private(set) var playingKey: String?

    var preferred: Source {
        didSet { UserDefaults.standard.set(preferred.rawValue, forKey: Self.sourceKey) }
    }

    var slow: Bool {
        didSet { UserDefaults.standard.set(slow, forKey: Self.slowKey) }
    }

    @ObservationIgnored private var player: AVAudioPlayer?
    /// Created on first use: spinning up the speech service can take seconds on a cold start.
    @ObservationIgnored private var speaker: AVSpeechSynthesizer?
    @ObservationIgnored private var sessionConfigured = false
    private let bundle: Bundle

    private static let sourceKey = "audio.source"
    private static let slowKey = "audio.slow"

    init(bundle: Bundle = .main) {
        self.bundle = bundle
        preferred = Source(rawValue: UserDefaults.standard.string(forKey: Self.sourceKey) ?? "") ?? .recorded
        slow = UserDefaults.standard.bool(forKey: Self.slowKey)
        super.init()
        loadManifest()
        refreshSystemVoice()
    }

    private var synthesizer: AVSpeechSynthesizer {
        if let speaker { return speaker }
        let made = AVSpeechSynthesizer()
        made.delegate = self
        speaker = made
        return made
    }

    var recordedAvailable: Bool { !(manifest?.clips.isEmpty ?? true) }
    var systemAvailable: Bool { systemVoice != nil }
    var recordedClipCount: Int { manifest?.clips.count ?? 0 }
    var recordedModel: String? { manifest?.model }

    /// What will actually play: the preferred source when it can, otherwise the other one.
    var effectiveSource: Source? {
        switch preferred {
        case .recorded: return recordedAvailable ? .recorded : (systemAvailable ? .system : nil)
        case .system: return systemAvailable ? .system : (recordedAvailable ? .recorded : nil)
        }
    }

    var canPlay: Bool { effectiveSource != nil }

    var systemVoiceDescription: String? {
        guard let voice = systemVoice else { return nil }
        let quality: String
        switch voice.quality {
        case .premium: quality = "Premium"
        case .enhanced: quality = "Enhanced"
        default: quality = "Default"
        }
        return "\(voice.name) (\(quality))"
    }

    /// Finds the best installed Gujarati voice off the main thread: the first call to speechVoices()
    /// loads the voice catalogue and can block for seconds.
    func refreshSystemVoice() {
        Task.detached(priority: .utility) {
            func rank(_ v: AVSpeechSynthesisVoice) -> Int {
                switch v.quality {
                case .premium: return 3
                case .enhanced: return 2
                default: return 1
                }
            }
            let identifier = AVSpeechSynthesisVoice.speechVoices()
                .filter { $0.language.lowercased().hasPrefix("gu") }
                .max { rank($0) < rank($1) }?
                .identifier
            await MainActor.run {
                self.systemVoice = identifier.flatMap { AVSpeechSynthesisVoice(identifier: $0) }
            }
        }
    }

    private func loadManifest() {
        guard let url = bundle.url(forResource: "manifest", withExtension: "json", subdirectory: "Audio"),
              let data = try? Data(contentsOf: url) else { return }
        manifest = try? JSONDecoder().decode(AudioManifest.self, from: data)
    }

    func hasClip(for request: AudioRequest) -> Bool { manifest?.clip(for: request) != nil }

    func play(_ request: AudioRequest) {
        stop()
        guard let source = effectiveSource else { return }
        configureSession()
        if source == .recorded, let clip = manifest?.clip(for: request),
           let url = bundle.url(forResource: (clip.file as NSString).deletingPathExtension,
                                withExtension: (clip.file as NSString).pathExtension, subdirectory: "Audio"),
           let player = try? AVAudioPlayer(contentsOf: url) {
            player.delegate = self
            player.enableRate = true
            player.rate = slow ? 0.8 : 1.0
            player.prepareToPlay()
            self.player = player
            playingKey = request.key
            player.play()
            return
        }
        guard let voice = systemVoice else { return }
        let utterance = AVSpeechUtterance(string: request.text)
        utterance.voice = voice
        utterance.rate = AVSpeechUtteranceDefaultSpeechRate * (slow ? 0.7 : 0.85)
        utterance.preUtteranceDelay = 0.05
        playingKey = request.key
        synthesizer.speak(utterance)
    }

    func stop() {
        player?.stop()
        player = nil
        if let speaker, speaker.isSpeaking { speaker.stopSpeaking(at: .immediate) }
        playingKey = nil
    }

    private func configureSession() {
        let session = AVAudioSession.sharedInstance()
        if !sessionConfigured {
            try? session.setCategory(.playback, mode: .spokenAudio, options: [.duckOthers])
            sessionConfigured = true
        }
        try? session.setActive(true)
    }

    /// A clip or utterance ended. Ignored if something newer has started since.
    fileprivate func finished(player id: ObjectIdentifier?) {
        if let id, let player, ObjectIdentifier(player) != id { return }
        if player?.isPlaying == true || speaker?.isSpeaking == true { return }
        player = nil
        playingKey = nil
        try? AVAudioSession.sharedInstance().setActive(false, options: .notifyOthersOnDeactivation)
    }
}

extension AudioService: AVAudioPlayerDelegate {
    nonisolated func audioPlayerDidFinishPlaying(_ player: AVAudioPlayer, successfully flag: Bool) {
        let id = ObjectIdentifier(player)
        Task { @MainActor in self.finished(player: id) }
    }
}

extension AudioService: AVSpeechSynthesizerDelegate {
    nonisolated func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didFinish utterance: AVSpeechUtterance) {
        Task { @MainActor in self.finished(player: nil) }
    }
}
